[case testTryExcept1]
def g() -> None:
    try:
        object()
    except:
        print("weeee")
[out]
def g():
    r0 :: object
    r1 :: str
    r2, r3 :: object
    r4 :: tuple[object, object, object]
    r5 :: str
    r6 :: object
    r7 :: str
    r8, r9 :: object
    r10 :: bool
L0:
L1:
    r0 = builtins :: module
    r1 = unicode_1 :: static  ('object')
    r2 = CPyObject_GetAttr(r0, r1)
    r3 = py_call(r2)
    goto L5
L2: (handler for L1)
    r4 = CPy_CatchError()
    r5 = unicode_2 :: static  ('weeee')
    r6 = builtins :: module
    r7 = unicode_3 :: static  ('print')
    r8 = CPyObject_GetAttr(r6, r7)
    r9 = py_call(r8, r5)
L3:
    CPy_RestoreExcInfo(r4)
    goto L5
L4: (handler for L2)
    CPy_RestoreExcInfo(r4)
    r10 = keep_propagating
    unreachable
L5:
    return 1

[case testTryExcept2]
def g(b: bool) -> None:
    try:
        if b:
            object()
        else:
            str('hi')
    except:
        print("weeee")
[out]
def g(b):
    b :: bool
    r0 :: object
    r1 :: str
    r2, r3 :: object
    r4, r5 :: str
    r6 :: tuple[object, object, object]
    r7 :: str
    r8 :: object
    r9 :: str
    r10, r11 :: object
    r12 :: bool
L0:
L1:
    if b goto L2 else goto L3 :: bool
L2:
    r0 = builtins :: module
    r1 = unicode_1 :: static  ('object')
    r2 = CPyObject_GetAttr(r0, r1)
    r3 = py_call(r2)
    goto L4
L3:
    r4 = unicode_2 :: static  ('hi')
    r5 = PyObject_Str(r4)
L4:
    goto L8
L5: (handler for L1, L2, L3, L4)
    r6 = CPy_CatchError()
    r7 = unicode_3 :: static  ('weeee')
    r8 = builtins :: module
    r9 = unicode_4 :: static  ('print')
    r10 = CPyObject_GetAttr(r8, r9)
    r11 = py_call(r10, r7)
L6:
    CPy_RestoreExcInfo(r6)
    goto L8
L7: (handler for L5)
    CPy_RestoreExcInfo(r6)
    r12 = keep_propagating
    unreachable
L8:
    return 1

[case testTryExcept3]
def g() -> None:
    try:
        print('a')
        try:
            object()
        except AttributeError as e:
            print('b', e)
    except:
        print("weeee")
[out]
def g():
    r0 :: str
    r1 :: object
    r2 :: str
    r3, r4, r5 :: object
    r6 :: str
    r7, r8 :: object
    r9 :: tuple[object, object, object]
    r10 :: object
    r11 :: str
    r12 :: object
    r13 :: bool
    e, r14 :: object
    r15 :: str
    r16 :: object
    r17 :: str
    r18, r19 :: object
    r20 :: bool
    r21 :: tuple[object, object, object]
    r22 :: str
    r23 :: object
    r24 :: str
    r25, r26 :: object
    r27 :: bool
L0:
L1:
    r0 = unicode_1 :: static  ('a')
    r1 = builtins :: module
    r2 = unicode_2 :: static  ('print')
    r3 = CPyObject_GetAttr(r1, r2)
    r4 = py_call(r3, r0)
L2:
    r5 = builtins :: module
    r6 = unicode_3 :: static  ('object')
    r7 = CPyObject_GetAttr(r5, r6)
    r8 = py_call(r7)
    goto L8
L3: (handler for L2)
    r9 = CPy_CatchError()
    r10 = builtins :: module
    r11 = unicode_4 :: static  ('AttributeError')
    r12 = CPyObject_GetAttr(r10, r11)
    r13 = CPy_ExceptionMatches(r12)
    if r13 goto L4 else goto L5 :: bool
L4:
    r14 = CPy_GetExcValue()
    e = r14
    r15 = unicode_5 :: static  ('b')
    r16 = builtins :: module
    r17 = unicode_2 :: static  ('print')
    r18 = CPyObject_GetAttr(r16, r17)
    r19 = py_call(r18, r15, e)
    goto L6
L5:
    CPy_Reraise()
    unreachable
L6:
    CPy_RestoreExcInfo(r9)
    goto L8
L7: (handler for L3, L4, L5)
    CPy_RestoreExcInfo(r9)
    r20 = keep_propagating
    unreachable
L8:
    goto L12
L9: (handler for L1, L6, L7, L8)
    r21 = CPy_CatchError()
    r22 = unicode_6 :: static  ('weeee')
    r23 = builtins :: module
    r24 = unicode_2 :: static  ('print')
    r25 = CPyObject_GetAttr(r23, r24)
    r26 = py_call(r25, r22)
L10:
    CPy_RestoreExcInfo(r21)
    goto L12
L11: (handler for L9)
    CPy_RestoreExcInfo(r21)
    r27 = keep_propagating
    unreachable
L12:
    return 1

[case testTryExcept4]
def g() -> None:
    try:
        pass
    except KeyError:
        print("weeee")
    except IndexError:
        print("yo")
[out]
def g():
    r0 :: tuple[object, object, object]
    r1 :: object
    r2 :: str
    r3 :: object
    r4 :: bool
    r5 :: str
    r6 :: object
    r7 :: str
    r8, r9, r10 :: object
    r11 :: str
    r12 :: object
    r13 :: bool
    r14 :: str
    r15 :: object
    r16 :: str
    r17, r18 :: object
    r19 :: bool
L0:
L1:
    goto L9
L2: (handler for L1)
    r0 = CPy_CatchError()
    r1 = builtins :: module
    r2 = unicode_1 :: static  ('KeyError')
    r3 = CPyObject_GetAttr(r1, r2)
    r4 = CPy_ExceptionMatches(r3)
    if r4 goto L3 else goto L4 :: bool
L3:
    r5 = unicode_2 :: static  ('weeee')
    r6 = builtins :: module
    r7 = unicode_3 :: static  ('print')
    r8 = CPyObject_GetAttr(r6, r7)
    r9 = py_call(r8, r5)
    goto L7
L4:
    r10 = builtins :: module
    r11 = unicode_4 :: static  ('IndexError')
    r12 = CPyObject_GetAttr(r10, r11)
    r13 = CPy_ExceptionMatches(r12)
    if r13 goto L5 else goto L6 :: bool
L5:
    r14 = unicode_5 :: static  ('yo')
    r15 = builtins :: module
    r16 = unicode_3 :: static  ('print')
    r17 = CPyObject_GetAttr(r15, r16)
    r18 = py_call(r17, r14)
    goto L7
L6:
    CPy_Reraise()
    unreachable
L7:
    CPy_RestoreExcInfo(r0)
    goto L9
L8: (handler for L2, L3, L4, L5, L6)
    CPy_RestoreExcInfo(r0)
    r19 = keep_propagating
    unreachable
L9:
    return 1

[case testTryFinally]
def a(b: bool) -> None:
    try:
        if b:
            raise Exception('hi')
    finally:
        print('finally')
[out]
def a(b):
    b :: bool
    r0 :: str
    r1 :: object
    r2 :: str
    r3, r4 :: object
    r5, r6, r7 :: tuple[object, object, object]
    r8 :: str
    r9 :: object
    r10 :: str
    r11, r12 :: object
    r13 :: bool
L0:
L1:
    if b goto L2 else goto L3 :: bool
L2:
    r0 = unicode_1 :: static  ('hi')
    r1 = builtins :: module
    r2 = unicode_2 :: static  ('Exception')
    r3 = CPyObject_GetAttr(r1, r2)
    r4 = py_call(r3, r0)
    CPy_Raise(r4)
    unreachable
L3:
L4:
L5:
    r6 = <error> :: tuple[object, object, object]
    r5 = r6
    goto L7
L6: (handler for L1, L2, L3)
    r7 = CPy_CatchError()
    r5 = r7
L7:
    r8 = unicode_3 :: static  ('finally')
    r9 = builtins :: module
    r10 = unicode_4 :: static  ('print')
    r11 = CPyObject_GetAttr(r9, r10)
    r12 = py_call(r11, r8)
    if is_error(r5) goto L9 else goto L8
L8:
    CPy_Reraise()
    unreachable
L9:
    goto L13
L10: (handler for L7, L8)
    if is_error(r5) goto L12 else goto L11
L11:
    CPy_RestoreExcInfo(r5)
L12:
    r13 = keep_propagating
    unreachable
L13:
    return 1

[case testWith]
from typing import Any
def foo(x: Any) -> None:
    with x() as y:
        print('hello')
[out]
def foo(x):
    x, r0, r1 :: object
    r2 :: str
    r3 :: object
    r4 :: str
    r5, r6 :: object
    r7 :: bool
    y :: object
    r8 :: str
    r9 :: object
    r10 :: str
    r11, r12 :: object
    r13, r14 :: tuple[object, object, object]
    r15, r16, r17, r18 :: object
    r19, r20 :: bool
    r21, r22, r23 :: tuple[object, object, object]
    r24, r25 :: object
    r26 :: bool
L0:
    r0 = py_call(x)
    r1 = PyObject_Type(r0)
    r2 = unicode_3 :: static  ('__exit__')
    r3 = CPyObject_GetAttr(r1, r2)
    r4 = unicode_4 :: static  ('__enter__')
    r5 = CPyObject_GetAttr(r1, r4)
    r6 = py_call(r5, r0)
    r7 = 1
L1:
L2:
    y = r6
    r8 = unicode_5 :: static  ('hello')
    r9 = builtins :: module
    r10 = unicode_6 :: static  ('print')
    r11 = CPyObject_GetAttr(r9, r10)
    r12 = py_call(r11, r8)
    goto L8
L3: (handler for L2)
    r13 = CPy_CatchError()
    r7 = 0
    r14 = CPy_GetExcInfo()
    r15 = r14[0]
    r16 = r14[1]
    r17 = r14[2]
    r18 = py_call(r3, r0, r15, r16, r17)
    r19 = bool r18 :: object
    if r19 goto L5 else goto L4 :: bool
L4:
    CPy_Reraise()
    unreachable
L5:
L6:
    CPy_RestoreExcInfo(r13)
    goto L8
L7: (handler for L3, L4, L5)
    CPy_RestoreExcInfo(r13)
    r20 = keep_propagating
    unreachable
L8:
L9:
L10:
    r22 = <error> :: tuple[object, object, object]
    r21 = r22
    goto L12
L11: (handler for L1, L6, L7, L8)
    r23 = CPy_CatchError()
    r21 = r23
L12:
    if r7 goto L13 else goto L14 :: bool
L13:
    r24 = builtins.None :: object
    r25 = py_call(r3, r0, r24, r24, r24)
L14:
    if is_error(r21) goto L16 else goto L15
L15:
    CPy_Reraise()
    unreachable
L16:
    goto L20
L17: (handler for L12, L13, L14, L15)
    if is_error(r21) goto L19 else goto L18
L18:
    CPy_RestoreExcInfo(r21)
L19:
    r26 = keep_propagating
    unreachable
L20:
    return 1

